### ISSUE TITLE
Using overlay workspace with vcstool/wstool?

### ISSUE THREAD

**Issue by gavanderhoorn** [Stanley-Robotics/rdmanifest#1]
Hi,

this is really more of a question, but I was wondering if you had any particular reasons for using rosdep manifests and installing to `/opt/ros` instead of going the 'normal' way with an (overlay) workspace and using something like [wstool](http://wiki.ros.org/wstool) or [vcstool](https://github.com/dirk-thomas/vcstool) with a `.rosinstall` file.

(I'm investigating workspace setup workflows, hence the question)

**Comment by lgeo3** [comment]
Hi @gavanderhoorn,

we weren't aware of the wstool solution when we start to use rdmanifest. Both setups seems to be well suited for the job (here, with rdmanifest we can use rosdep install in order to get the dependances), but in the other hand, wstool seems to be good too.

For the future we may start using wstool, thanks to your comment. 
If you have more information about the pro/cons of each we will be happy to know it.

Thanks again.

Laurent

**Comment by gavanderhoorn** [comment]
@laurent-george wrote:

> here, with rdmanifest we can use rosdep install in order to get the dependances

As far as I know, `rosdep` uses the information in the `package.xml` files, so it should be able to do this with `.rosinstall` files and `wstool` as well. The two are orthogonal.

The big difference with `.rdmanifest` is that you can add whatever commands you want in there. That goes much further than installing just some dependencies. It also seems less 'safe' in a way. Specifying specific versions or tags to checkout can be done with both.

I think `.rosinstall` with either `wstool` or `vcstool` (which also still supports those files) is currently considered 'best practice'. `.rdmanifest`, while not explicitly marked deprecated, seems like something that is not used much any more. `rosdep` is still used, but support for running arbitrary commands in the mapping db of that tool has also been removed / is not encouraged anymore.

Typical workflow these days:
1. create workspace directory layout: `mkdir -p /path/to/catkin_ws/src`
2. `git clone ..` repositories, _or_ populate the source space using `wstool merge <uri>`
3. `cd /path/to/catkin_ws`
4. `catkin_make` or `catkin build`
5. `source /path/to/catkin_ws/devel/setup.bash`

Such a workspace _overlays_ the default `/opt/ros/$distro` install space, but the same steps can be done using any workspace as base (ie: some other workspace containing a set of from-sources-built pkgs that are needed but shouldn't live in the developer's workspace).

The overlay workspace setup would allow you to build those `ros_canopen`, `smach` and `velodyne` forks, without having to install them globally into `/opt/ros/..` (no need for `sudo` or circumventing the package manager anymore).
